server:
  port: 8081

spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://123.56.26.20:3308/share_img?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8
    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
      max-file-size: 10000MB
      max-request-size: 10000MB
mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: com.xxkj.myuploader

upload:
  path: ./upload/